name: publish-container-image

on:
  push:
    branches: [ main ]
  release:
    types: [ released, prereleased ]

jobs:
  publish-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Publish Container Image
        run: |
          # login to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          # build image
          docker build . --tag ghcr.io/eclipse-opensmartclide/smartclide/external-project-importer:$(date +'%Y-%m-%d')
          # push image
          docker push ghcr.io/eclipse-opensmartclide/smartclide/external-project-importer:$(date +'%Y-%m-%d')
